version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: fleet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fleet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: fleet
    ports:
      - "8088:8080"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app          # mount code host v√†o container
      - /app/tmp                # tmp cho air
    command: air -c .air.toml 

  frontend:
    build: ./fontend
    container_name: fleet_frontend
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8088/api
    depends_on:
      - backend
    volumes:
      - ./fontend:/app
      - /app/node_modules
volumes:
  db_data:
